[DEFAULT]
# General Oauth Config
oauth_secret=TZL(\S=z.w<fe=UaLdfsdfsewe:Z[ojsdfE6Nr1mz&53`K^fw
# Azure AD Config
azure_ad_device_endpoint=https://login.microsoftonline.com/18a59a81-eea8-4c30-948a-d8824cdc2580/oauth2/v2.0/devicecode
azure_ad_token_endpoint=https://login.microsoftonline.com/18a59a81-eea8-4c30-948a-d8824cdc2580/oauth2/v2.0/token

[DEV]
# Azure AD Config
azure_ad_client_id=94186d2d-29ee-4e16-9662-78d3a10eace1
azure_ad_scope=api://0ff51fc9-0fa7-4aba-83c7-5583346e0886/main openid offline_access

[QA]
# Azure AD Config
azure_ad_client_id=9f61bdb6-95df-4f63-a95d-f08b319d8188
azure_ad_scope=api://0ff51fc9-0fa7-4aba-83c7-5583346e0886/main openid offline_access

[PRD]
# Azure AD Config
azure_ad_client_id=2141174f-0236-464a-8088-5a72f1082010
azure_ad_scope=api://c1f276b2-a7ff-41ff-9b7f-8fcb979b8e1a/main openid offline_access